# Generated by Django 4.2.5 on 2023-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='desciption',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
